BEGIN;

DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS operators CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS contractors CASCADE;
DROP TABLE IF EXISTS license_plates CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;

COMMIT;