basePath: /api/v1
consumes:
    - application/json
definitions:
    ErrorMessage:
        title: ErrorMessage is a detailed error message.
        x-go-package: github.com/maaw77/crmsrvg/internal/handlers/v1
    GsmTableEntry:
        description: GsmTableEntry defines the structure for the entry in the GSM table
        x-go-package: github.com/maaw77/crmsrvg/internal/models
    IdEntry:
        x-go-package: github.com/maaw77/crmsrvg/internal/models
info:
    contact:
        email: maaw@mai.ru
    description: Documentation for REST API
    license:
        name: MIT
        url: http://opensource.org/licenses/MIT
    title: CRM Server
    version: 1.0.0
paths:
    /:
        get:
            description: |-
                Default Handler for everything that is not a match.
                Works with all HTTP methods
            operationId: defaultHandler
            responses:
                "404":
                    description: ErrorMessage
                    schema:
                        $ref: '#/definitions/ErrorMessage'
            security:
                - api_key:
                    - '[]'
            summary: defaultHandler
    /*:
        get:
            description: |-
                Default Handler for endpoints used with incorrect HTTP request method.
                Works with all paths and HTTP methods
            operationId: methodNotAllowed
            responses:
                "405":
                    description: ErrorMessage
                    schema:
                        $ref: '#/definitions/ErrorMessage'
            summary: methodNotAllowed
    /gsm_table:
        post:
            description: Adds an entry to the GSM table
            operationId: paramGsmTableEntry
            parameters:
                - description: The structure for the entry in the GSM table
                  in: body
                  name: Body
                  schema: {}
            produces:
                - application/json
            responses:
                "200":
                    description: IdEntry
                    schema:
                        $ref: '#/definitions/IdEntry'
                "400":
                    description: ErrorMessage
                    schema:
                        $ref: '#/definitions/ErrorMessage'
            summary: addEntryGsm
            tags:
                - GSM
    /gsm_table/date/{date}:
        get:
            description: Receives aan entry with a specified date from the GSM table
            operationId: paramCrmDate
            parameters:
                - description: It is a date  based on the specified layout ("2006-01-02")
                  format: date
                  in: path
                  name: date
                  required: true
                  type: string
                  x-go-name: DATE
            produces:
                - application/json
            responses:
                "200":
                    description: GsmTableEntry
                    schema:
                        $ref: '#/definitions/GsmTableEntry'
                "404":
                    description: ErrorMessage
                    schema:
                        $ref: '#/definitions/ErrorMessage'
            summary: getDateEntryGsm
            tags:
                - GSM
    /gsm_table/id/{id}:
        get:
            description: Receives an entry with a specified ID from the GSM table
            operationId: paramIdEntry
            parameters:
                - description: ID of the database entry
                  format: int64
                  in: path
                  minimum: 1
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            produces:
                - application/json
            responses:
                "200":
                    description: GsmTableEntry
                    schema:
                        $ref: '#/definitions/GsmTableEntry'
                "404":
                    description: ErrorMessage
                    schema:
                        $ref: '#/definitions/ErrorMessage'
            summary: getIdEntryGsm
            tags:
                - GSM
produces:
    - application/json
schemes:
    - http
securityDefinitions:
    api_key:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
