basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: maaw@mail.ru
    name: Maaw
  description: Fuel and Lubricants Accounting Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CRM server
  version: "1.0"
paths: {}
swagger: "2.0"
